from routes.maquina import Maquina
from routes.stock import Stock
from routes.talao import Talao
from routes.premio import Premio
from routes.cliente import Cliente
from routes.funcionario import Funcionario
from routes.admin import Admin
from routes.login import Login
from routes.setup import Setup
from routes.levantamento import Levantamento